### ISSUE TITLE
Use hash free links

### ISSUE THREAD

**Issue by tomwayson** [tomwayson/esri-react-router-example#10]
See [this tutorial](https://github.com/reactjs/react-router-tutorial/tree/master/lessons/10-clean-urls). May require some tweaks to the build and gh-pages deploy scripts.

**Comment by davetimmins** [comment]
I had a quick look at this and using `browserHistory` works fine, need to add this to the webpack config too.

```
devServer: {
  historyApiFallback: true
}
```

I didnt look at the gh-pages deployment but a quick google came up with this whch looks promising https://github.com/rafrex/spa-github-pages

**Comment by tomwayson** [comment]
Thanks for validating that it would work and doing the research on that @davetimmins!

It looks like this would add complexity that might obscure what I'm trying to demonstrate w/ this example app, so will probably leave it as is for now and make this lower priority.
