### ISSUE TITLE
Outdated possibly?

### ISSUE THREAD

**Issue by CraigglesO** [tomwayson/esri-react-router-example#33]
I had problems with:  [this part of your code](https://github.com/tomwayson/esri-react-router-example/blob/master/modules/Map.js#L47)

it just wouldn't load the module (maybe it doesn't exist in 4.5?)

with 4.5 I was able to achieve the same thing with:
```
componentDidMount () {
    // get item id from route params or use default
    const itemId = '8e42e164d4174da09f61fe0d3f206641';
    dojoRequire(['esri/WebMap', 'esri/views/MapView'], (WebMap, MapView) => {
      let webmap = new WebMap({
        portalItem: { id: itemId }
      });
      new MapView({
        container: this.refs.map,
        map: webmap
      });
    });
  }
```

Hope this helps.

**Comment by tomwayson** [comment]
Correct, the code in this repo uses a 3.x version of the ArcGIS API

https://github.com/tomwayson/esri-react-router-example/blob/8c042961aca2dc7dff723cf36f3505e3d3dc3e50/modules/App.js#L16

Glad you were able to figure it out.
